# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Zac Manchester
tagline:             'Rocket Scientist, Engineer, Bass Player'
description:         'Zac's Homepage'
url:                 http://zacmanchester.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Zac Manchester
  url:               http://zacmanchester.com
  email:             zacinaction@gmail.com

# Custom vars
version:             1.0.0
